<a href="https://colab.research.google.com/github/Vaibhav074N/Assigement-26Feb/blob/main/Assigement_Feb26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1 & Q2

In [1]:
import numpy as np

In [4]:
list1 = ['1','2','3','4','5']
array_list = np.array(object = list1)
print(array_list)

['1' '2' '3' '4' '5']


In [7]:
print(type(list1))
print(list1)
# it is type list

<class 'list'>
['1', '2', '3', '4', '5']


In [6]:
print(type(array_list))
# it is a 1 dimensional array

<class 'numpy.ndarray'>


In [9]:
for i in list1:
  print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [10]:
for j in array_list:
  print(type(j))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3.

In [12]:
array_list = np.array(object = list1 , dtype = int)
# by defining dtype is equal to int the data type in array_list will be integer and in variable reamins same as str.

In [13]:
print(type(array_list))

<class 'numpy.ndarray'>


In [14]:
for i in array_list:
  print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q4.

In [23]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
print(num_list)

[[1, 2, 3], [4, 5, 6]]


In [18]:
num_array = np.array(object = num_list)
print(num_array)

[[1 2 3]
 [4 5 6]]


In [20]:
num_array.shape

(2, 3)

In [21]:
num_array.size

6

Q5.

In [26]:
import numpy.matlib as nm
a = nm.zeros((3,3))

In [27]:
a

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [28]:
a.size

9

Q6.

In [31]:
b = nm.eye((5))

In [32]:
b

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [33]:
b.shape

(5, 5)